swagger: '2.0'

info:
  version: '1.0'
  title: Example Users Service
  description: This is an example spec for a Users Service

host: api.fortellis.io
basePath: /example/v1/users
schemes:
 - https

paths:
  /health:
    get:
      summary: health
      description: health
      operationId: health
      parameters:
        - $ref: '#/parameters/header.Authorization'
        - $ref: '#/parameters/header.Subscription-Id'
      produces:
        - application/json
      responses:
        200:
          description: OK
          headers:
            Content-Language:
              type: string
            Content-Type:
              type: string
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
  /:
    get:
      summary: Get all users
      description: Get all users
      operationId: getUsers
      parameters:
        - $ref: '#/parameters/header.Authorization'
        - $ref: '#/parameters/header.Subscription-Id'
      produces:
        - application/json
      responses:
        200:
          description: OK
          headers:
            Content-Language:
              type: string
            Content-Type:
              type: string
          schema:
            $ref: '#/definitions/matchResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'  
  /{id}:
    get:
      summary: Get user by Id
      description: Get user by Id
      operationId: getUserById
      parameters:
      - $ref: '#/parameters/header.Authorization'
      - $ref: '#/parameters/header.Subscription-Id'
      - name: id
        in: path
        required: true
        description: The id for the specific user being requested.
        type: string
      produces:
        - application/json
      responses:
        200:
          description: OK
          headers:
            Content-Language:
              type: string
            Content-Type:
              type: string
          schema:
            $ref: '#/definitions/matchResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'                        
  /match:
    post:
      summary: Match
      description: Match
      operationId: match
      parameters:
      - $ref: '#/parameters/header.Authorization'
      - $ref: '#/parameters/header.Subscription-Id'
      - in: body
        name: userProfile
        description: User profile to match
        schema:
          $ref: '#/definitions/payload'
      produces:
        - application/json
      responses:
        200:
          description: OK
          headers:
            Content-Language:
              type: string
            Content-Type:
              type: string
          schema:
            $ref: '#/definitions/matchResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'


parameters:
  header.Authorization:
    name: Authorization
    in: header
    required: true
    type: string
    description: Provide authorization to access Fortellis APIs. This must be an OAuth 2.0 token for calling a Fortellis Provider but you may call the simulator platform with basic auth using your API key and secret.
  header.Subscription-Id:
    name: Subscription-Id
    in: header
    required: true
    type: string
    description: The Fortellis Marketplace subscription identifier between a user entity and the solution. For sample responses use the Subscription-Id 'test' and your solution's apikey.

  
definitions:

  # Properties
  id:
    type: string
  firstname:
    type: string
  lastname:
    type: string
  dob:
    type: string
  phone:
    type: string
  orgId:
    type: string
  email:
    type: string



  # Request
  payload:
    properties:
      firstname:
        $ref: '#/definitions/firstname'
      lastname: 
        $ref: '#/definitions/lastname'
      orgId: 
        $ref: '#/definitions/orgId'
      email: 
        $ref: '#/definitions/email'
      phone: 
        $ref: '#/definitions/phone'        
    required:
      - firstname
      - lastname
    example:
      firstname: 'John'
      lastname: 'Doe'
      orgid: '9999'
      email: 'john.doe@mail.com'
      phone: '888-555-4444'
    

  # Response
  matchResponse:
    type: object
    properties:
      data:
        type: array
        description: Array of users
        items:
          properties:
            name:
              $ref: '#/definitions/id'
            firstname:
              $ref: '#/definitions/firstname'
            lastname: 
              $ref: '#/definitions/lastname'
            dob: 
              $ref: '#/definitions/dob'
            phone: 
              $ref: '#/definitions/phone'
            email: 
              $ref: '#/definitions/email'
            orgId: 
              $ref: '#/definitions/orgId'
    example:
      id: '123'
      firstname: 'John'
      lastname: 'Doe'
      dob: '01/01/1999'
      phone: '888-555-4444'
      email: 'john.doe@mail.com'
      orgId: '9999'
      

  # Common
  ErrorResponse:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    required:
      - code
      - message
